{
  "name": "cf-vue",
  "compatibility_date": "2024-12-30",
  "assets": {
    "binding": "ASSETS",
    "not_found_handling": "single-page-application"
  },
  "main": "./api/index.js",
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "cf-vue",
      "database_id": "isi"
    }
  ]
}