name = "cf-vue-2"
main = "api/index.js"
compatibility_date = "2024-12-30"

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "cf-vue-2"
database_id = "ISI_DENGAN_ID_DARI_DASHBOARD"
