name = "cf-vue"
compatibility_date = "2024-12-30"
main = "./api/index.js"

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "cf-vue"
database_id = "ffd42e63-ca23-4243-8757-bbd6b5ddcd42"
